### ISSUE TITLE
[Analytics] Addition of Google Analytics

### ISSUE THREAD

**Issue by Pk13055** [Pk13055/stocks-app#1]
We have two options for this:
- Either we go with the default JS based Google analytics
- Use a python package to have some control over the data from the Django backend

**Comment by mayankrasu** [comment]
I would prefer whichever is easier and more compatible with our website infrastructure.

**Comment by Pk13055** [comment]
I will checkout what the Django package has to offer. If it seems more beneficial, we can go with that. Else the javascript addition is quite easy, albeit you'll be using the Google dashboard for monitoring.

**Comment by mayankrasu** [comment]
That's fine. I don't mind using Google dashboard.

**Comment by Pk13055** [comment]
@mayankrasu  ~What's the tracking code?~ Added the same tracking code as the one you had committed, please check whether the analytics is working fine; we can close this issue.

**Comment by Pk13055** [comment]
Added as of `14b79688e46f50db520030f49909e7702ade5e65]`
